name: Collin Asmus
favicon: null
layout_spectrum: 0.37363
typography_spectrum: 0.69257
title: Peronal website of Collinasmus.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#303332'
    - '#635b57'
    - '#1b2428'
    - '#1a111b'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
