name: Collin Asmus
favicon: null
layout_spectrum: 0.28627
typography_spectrum: 0.69257
title: Collin Asmus
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#323232'
    - '#6c6c6c'
    - '#c6c6c6'
    - '#0a0a0a'
  brandStrength: 0.375
  lightness: 0.0625
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose: []
