name: Collin Asmus
favicon: null
layout_spectrum: 0.37363
typography_spectrum: 0.69257
title: Peronal website of Collinasmus.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#3e3f5d'
    - '#7f6b6d'
    - '#b1a2a7'
    - '#e7e1e3'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
